version: '3.7'

networks:
  default:
    name: ntu-network

services:
  # access-nginx:
  #   image: gitlab.iot.webbylab.com:5050/2smart/propuskator/services/nginx:${TAG:-release}
  #   container_name: access-nginx
  #   restart: always
  #   depends_on:
  #     - ssl-certs
  #   volumes:
  #     - ${ROOT_DIR:-.}/system/ssl:/etc/nginx/ssl
  #     - ${ROOT_DIR:-.}/system/releases:/var/tmp/releases
  #     - ${ROOT_DIR:-.}/system/shared/nginx:/var/tmp/shared
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - TELEGRAM_BOT_SECRET_PATH=${TELEGRAM_BOT_TOKEN}
  #     - MODE=${NGINX_MODE:-default}
  #     - REDIRECT_FROM_IP=${NGINX_REDIRECT_FROM_IP}
  #     - REDIRECT_TO_HOSTNAME=${NGINX_REDIRECT_TO_HOSTNAME}
  #     - NGINX_SSL_CERT=${NGINX_SSL_CERT}
  #     - NGINX_SSL_CERT_KEY=${NGINX_SSL_CERT_KEY}
  #   ports:
  #     - ${NGINX_HTTP_PORT:-80}:80
  #     - ${NGINX_HTTPS_PORT:-443}:443

  percona:
    build: ../percona/
    container_name: percona
    restart: always
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ=${TIMEZONE}
    volumes:
      - ${PWD:-.}/system/mysql:/var/lib/mysql
  nginx:
    build: ../nginx/
    container_name: nginx
    restart: always
    environment:
      TZ: ${TIMEZONE:-Europe/Kiev}
      MODE: ${NGINX_MODE:-default}
    volumes:
      - ${PWD}/system/ssl:/etc/nginx/ssl
      - ${PWD}/system/releases:/var/tmp/releases
      - ${PWD}/system/releases-mobile:/var/www/static/releases-mobile
      - ${PWD}/system/wizard-instructions:/var/www/static/wizard-instructions
      - ${PWD}/system/shared/nginx:/var/tmp/shared
    ports:
      - 80:80


  # ssl-certs:
  #   image: gitlab.iot.webbylab.com:5050/2smart/propuskator/services/ssl-certs:${TAG:-release}
  #   container_name: ssl-certs
  #   environment:
  #     - DNS=${DNS:-localhost}
  #   volumes:
  #     - ${ROOT_DIR:-.}/system/ssl/certs:/app/certs
  #     - ${ROOT_DIR:-.}/system/ssl/private:/app/private
  ui:
    build: ../ui/
    container_name: ui
    restart: always
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:8000}
      - API_PREFIX=${API_PREFIX:-/api/v1/admin/}
      - UPDATER_API_URL=${UPDATER_API_URL:-.}
      - UPDATER_API_PREFIX=${UPDATER_API_PREFIX:-/updater/v1/}
      - TZ=${TIMEZONE}
    ports:
      - 3000:80
  backend:
    build: ../be/
    container_name: backend
    restart: always
    command: sh -c "npm run migration:db && npm start"
    environment:
      - WAIT_HOSTS=${DB_HOST:-percona}:${DB_PORT:-3306}
      - DNS=${DNS:-localhost}
      - API_URL=${API_URL}
      - DEEP_LINK_HOST_URL=${DEEP_LINK_HOST_URL}
      - PORT=${PORT:-8000}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ADMIN_PASSWORD_RESET_TOKEN_SECRET=${ADMIN_PASSWORD_RESET_TOKEN_SECRET}
      - MOBILE_PASSWORD_RESET_TOKEN_SECRET=${MOBILE_PASSWORD_RESET_TOKEN_SECRET}
      - DB_NAME=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST:-access-percona}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DIALECT=${DB_DIALECT:-mysql}
      - TZ=${TIMEZONE}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - TOKEN_READER_ACTIVE_PERIOD_SECONDS=${TOKEN_READER_ACTIVE_PERIOD_SECONDS:-180}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME:-1200}
      - ROOT_SSL_CERT_PATH=${ROOT_SSL_CERT_PATH:-/app/etc/ssl/certs/ca.pem}
      - MAIL_OPTIONS_TRANSPORT_TYPE=${MAIL_OPTIONS_TRANSPORT_TYPE:-SMTP}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_PORT=${MAIL_OPTIONS_TRANSPORT_OPTIONS_PORT:-}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_HOST=${MAIL_OPTIONS_TRANSPORT_OPTIONS_HOST}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_USER=${MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_USER}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_PASS=${MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_PASS}
      - MAIL_OPTIONS_FROM=${MAIL_OPTIONS_FROM}
      - REPORT_RECIEVER_EMAIL=${REPORT_RECIEVER_EMAIL}
      - REPORT_SEND_INTERVAL=${REPORT_SEND_INTERVAL}
      - CHECK_STREAMS_INTERVAL_MS=${CHECK_STREAMS_INTERVAL_MS:-30000}
      - CHECK_STREAMS_TIMEOUT_MS=${CHECK_STREAMS_TIMEOUT_MS:-5000}
      - FAILED_CHECK_STREAM_RETRIES=${FAILED_CHECK_STREAM_RETRIES:-3}
      - RESET_PASSWORD_INTERVAL=${RESET_PASSWORD_INTERVAL:-300}
      - COLLECT_FRAMES_INTERVAL=${COLLECT_FRAMES_INTERVAL:-300000}
      - COLLECT_FRAMES_CONCURRENT_PROCS_NUMBER=${COLLECT_FRAMES_CONCURRENT_PROCS_NUMBER:-5}
      - COLLECT_FRAMES_PROC_TIMEOUT=${COLLECT_FRAMES_PROC_TIMEOUT:-60000}
      - ATTEMPTS_INTERVAL=${ATTEMPTS_INTERVAL:-60}
      - ATTEMPTS_COUNT=${ATTEMPTS_COUNT:-5}
      - ATTEMPTS_BLOCKED_TIME=${ATTEMPTS_BLOCKED_TIME:-300}
      - DEFAULT_ENVS_FILE_PATH=${DEFAULT_ENVS_FILE_PATH:-/app/.env.defaults}
      - READER_PHONE_NUMBERS=${READER_PHONE_NUMBERS}
      - MQTT_SYNC_MAX_DELAY=${MQTT_SYNC_MAX_DELAY:-10000}
      - MQTT_SYNC_RESET_TIMEOUT=${MQTT_SYNC_RESET_TIMEOUT:-1000}
      - MEDIA_DIR_PATH=${MEDIA_DIR_PATH:-/app/media}
      - S3_ENDPOINT=http://${MINIO_HOST}:${MINIO_PORT}
      - S3_BUCKET=${MINIO_BUCKET}
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - LOGS_RECORDED_FRAMES_TO_SAVE_NUMBER=${LOGS_RECORDED_FRAMES_TO_SAVE_NUMBER:-3}
      - LOGS_RECORDED_VIDEOS_TO_SAVE_NUMBER=${LOGS_RECORDED_VIDEOS_TO_SAVE_NUMBER:-2}
      - SERVICES_TOKEN_LIFETIME=${SERVICES_TOKEN_LIFETIME:-1200}
      - USER_REQUESTS_REGISTRATION_ATTEMPTS_COUNT=${USER_REQUESTS_REGISTRATION_ATTEMPTS_COUNT}
    volumes:
      - ${PWD:-.}/system/storage:/app/storage
      - ${PWD:-.}/system/ssl/certs:/app/etc/ssl/certs

  # access-backups:
  #   image: gitlab.iot.webbylab.com:5050/2smart/propuskator/apps/backups:${TAG:-release}
  #   container_name: access-backups
  #   restart: always
  #   environment:
  #     - MYSQL_HOST=${DB_HOST}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #     - BACKUPS_DIR_PATH=${BACKUPS_DIR_PATH}
  #     - BACKUPS_LIFE_DAYS=${BACKUPS_LIFE_DAYS:-30}
  #     - STORAGE_DIR_PATH=${STORAGE_DIR_PATH:-/app/storage}
  #     - TZ=${TIMEZONE}
  #     - UPLOAD_BACKUPS_TO_DO=${UPLOAD_BACKUPS_TO_DO:-0}
  #     - DO_SPACE_ENDPOINT=${DO_SPACE_ENDPOINT}
  #     - DO_SPACE_ACCESS_KEY_ID=${DO_SPACE_ACCESS_KEY_ID}
  #     - DO_SPACE_SECRET_ACCESS_KEY=${DO_SPACE_SECRET_ACCESS_KEY}
  #     - DO_SPACE_BUCKET=${DO_SPACE_BUCKET}
  #     - DO_SPACE_ROOT_PROJECT_FOLDER=${DO_SPACE_ROOT_PROJECT_FOLDER}
  #     - ENCRYPT_KEYS_EMAIL=${ENCRYPT_KEYS_EMAIL}
  #     - ENCRYPT_KEYS_FOLDER=${ENCRYPT_KEYS_FOLDER:-/app/keys}
  #     - GPG_PUBLIC_KEY_FILENAME=${GPG_PUBLIC_KEY_FILENAME:-public_key.gpg}
  #     # controls whether to create daily/weekly/monthly backups, set to "1" if yes
  #     - BACKUP_DAILY=${BACKUP_DAILY:-1}
  #     - BACKUP_WEEKLY=${BACKUP_WEEKLY:-1}
  #     - BACKUP_MONTHLY=${BACKUP_MONTHLY:-1}
    # volumes:
    #   - ${ROOT_DIR:-.}/system/backups:${BACKUPS_DIR_PATH}
    #   - ${ROOT_DIR:-.}/system/keys:${ENCRYPT_KEYS_FOLDER:-/app/keys}
    #   - ${ROOT_DIR:-.}/system/storage:${STORAGE_DIR_PATH:-/app/storage}
  # access-minio:
  #   image: gitlab.iot.webbylab.com:5050/2smart/propuskator/services/minio:${TAG:-release}
  #   container_name: access-minio
  #   restart: always
  #   command: minio server /data
  #   environment: 
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
  #   volumes:
  #     - ${ROOT_DIR}/system/minio:/data
  # access-minio-client:
  #   image: gitlab.iot.webbylab.com:5050/2smart/propuskator/services/minio-client:${TAG:-release}
  #   container_name: access-minio-client
  #   depends_on: 
  #     - access-minio
  #   environment:
  #     - MINIO_HOST=${MINIO_HOST}
  #     - MINIO_PORT=${MINIO_PORT}
  #     - MINIO_BUCKET=${MINIO_BUCKET}
  #     - MINIO_ROOT_USER=${MINIO_ROOT_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}