version: '3.7'

networks:
  default:
    name: ntu-network
services:
  percona:
    build: ../percona/
    container_name: percona
    restart: always
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ=${TIMEZONE}
    volumes:
      - ${PWD:-.}/system/mysql:/var/lib/mysql
  nginx:
    build: ../nginx/
    container_name: nginx
    restart: always
    environment:
      TZ: ${TIMEZONE:-Europe/Kiev}
      MODE: ${NGINX_MODE:-default}
    volumes:
      - ${PWD}/system/ssl:/etc/nginx/ssl
      - ${PWD}/system/releases:/var/tmp/releases
      - ${PWD}/system/releases-mobile:/var/www/static/releases-mobile
      - ${PWD}/system/wizard-instructions:/var/www/static/wizard-instructions
      - ${PWD}/system/shared/nginx:/var/tmp/shared
    ports:
      - 80:80
  ui:
    build: ../ui/
    container_name: ui
    restart: always
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:8000}
      - API_PREFIX=${API_PREFIX:-/api/v1/admin/}
      - UPDATER_API_URL=${UPDATER_API_URL:-.}
      - UPDATER_API_PREFIX=${UPDATER_API_PREFIX:-/updater/v1/}
      - TZ=${TIMEZONE}
    ports:
      - 3000:80
  backend:
    build: ../be/
    container_name: backend
    restart: always
    command: sh -c "npm run migration:db && npm start"
    environment:
      - WAIT_HOSTS=${DB_HOST:-percona}:${DB_PORT:-3306}
      - DNS=${DNS:-localhost}
      - API_URL=${API_URL}
      - DEEP_LINK_HOST_URL=${DEEP_LINK_HOST_URL}
      - PORT=${PORT:-8000}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ADMIN_PASSWORD_RESET_TOKEN_SECRET=${ADMIN_PASSWORD_RESET_TOKEN_SECRET}
      - MOBILE_PASSWORD_RESET_TOKEN_SECRET=${MOBILE_PASSWORD_RESET_TOKEN_SECRET}
      - DB_NAME=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST:-access-percona}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DIALECT=${DB_DIALECT:-mysql}
      - TZ=${TIMEZONE}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - TOKEN_READER_ACTIVE_PERIOD_SECONDS=${TOKEN_READER_ACTIVE_PERIOD_SECONDS:-180}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME:-1200}
      - ROOT_SSL_CERT_PATH=${ROOT_SSL_CERT_PATH:-/app/etc/ssl/certs/ca.pem}
      - MAIL_OPTIONS_TRANSPORT_TYPE=${MAIL_OPTIONS_TRANSPORT_TYPE:-SMTP}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_PORT=${MAIL_OPTIONS_TRANSPORT_OPTIONS_PORT:-}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_HOST=${MAIL_OPTIONS_TRANSPORT_OPTIONS_HOST}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_USER=${MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_USER}
      - MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_PASS=${MAIL_OPTIONS_TRANSPORT_OPTIONS_AUTH_PASS}
      - MAIL_OPTIONS_FROM=${MAIL_OPTIONS_FROM}
      - REPORT_RECIEVER_EMAIL=${REPORT_RECIEVER_EMAIL}
      - REPORT_SEND_INTERVAL=${REPORT_SEND_INTERVAL}
      - CHECK_STREAMS_INTERVAL_MS=${CHECK_STREAMS_INTERVAL_MS:-30000}
      - CHECK_STREAMS_TIMEOUT_MS=${CHECK_STREAMS_TIMEOUT_MS:-5000}
      - FAILED_CHECK_STREAM_RETRIES=${FAILED_CHECK_STREAM_RETRIES:-3}
      - RESET_PASSWORD_INTERVAL=${RESET_PASSWORD_INTERVAL:-300}
      - COLLECT_FRAMES_INTERVAL=${COLLECT_FRAMES_INTERVAL:-300000}
      - COLLECT_FRAMES_CONCURRENT_PROCS_NUMBER=${COLLECT_FRAMES_CONCURRENT_PROCS_NUMBER:-5}
      - COLLECT_FRAMES_PROC_TIMEOUT=${COLLECT_FRAMES_PROC_TIMEOUT:-60000}
      - ATTEMPTS_INTERVAL=${ATTEMPTS_INTERVAL:-60}
      - ATTEMPTS_COUNT=${ATTEMPTS_COUNT:-5}
      - ATTEMPTS_BLOCKED_TIME=${ATTEMPTS_BLOCKED_TIME:-300}
      - DEFAULT_ENVS_FILE_PATH=${DEFAULT_ENVS_FILE_PATH:-/app/.env.defaults}
      - READER_PHONE_NUMBERS=${READER_PHONE_NUMBERS}
      - MQTT_SYNC_MAX_DELAY=${MQTT_SYNC_MAX_DELAY:-10000}
      - MQTT_SYNC_RESET_TIMEOUT=${MQTT_SYNC_RESET_TIMEOUT:-1000}
      - MEDIA_DIR_PATH=${MEDIA_DIR_PATH:-/app/media}
      - S3_ENDPOINT=http://${MINIO_HOST}:${MINIO_PORT}
      - S3_BUCKET=${MINIO_BUCKET}
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - LOGS_RECORDED_FRAMES_TO_SAVE_NUMBER=${LOGS_RECORDED_FRAMES_TO_SAVE_NUMBER:-3}
      - LOGS_RECORDED_VIDEOS_TO_SAVE_NUMBER=${LOGS_RECORDED_VIDEOS_TO_SAVE_NUMBER:-2}
      - SERVICES_TOKEN_LIFETIME=${SERVICES_TOKEN_LIFETIME:-1200}
      - USER_REQUESTS_REGISTRATION_ATTEMPTS_COUNT=${USER_REQUESTS_REGISTRATION_ATTEMPTS_COUNT}
    volumes:
      - ${PWD:-.}/system/storage:/app/storage
      - ${PWD:-.}/system/ssl/certs:/app/etc/ssl/certs